os:
  open: "xterm -e nvim {{filename}}"
  edit: "nvim {{filename}}"
customCommands:
  - key: "O"
    description: "Open with 'vim' config in new terminal"
    command: "xterm -e sh -c 'nvim --noplugin {{.SelectedFile.Name}}' > /dev/null 2>&1"
    context: "files"
    output: terminal
  - key: "E"
    description: "Edit with 'vim' config"
    command: "nvim --noplugin {{.SelectedFile.Name}}"
    context: "files"
    output: terminal
