db_path = "~/.history.db"

filter_mode = "global" # session/global/directory/host

filter_mode_shell_up_key_binding = "session" # session/global/directory/host

key_path = "~/.key"

session_path = "~/.session"

dialect = "us"

style = "compact"

inline_height = 10

auto_sync = true

update_check = true

sync_address = "https://api.atuin.sh"

sync_frequency = "1h"

history_filter = [
  "^y$",
  "^z$",
  "^cd$",
  "^sp$",
  "^vi$",
  "^xr$",
  "^ls$",
  "^lzg$",
  "^rex$",
  "^fzf$",
  "^lzg$",
  "^lzd$",
  "^nvim$",
  "^clear",
]

cwd_filter = ["^/very/secret/area"]

max_preview_height = 4

show_help = true

secrets_filter = true

enter_accept = true

common_subcommands = ["cargo", "go", "git", "npm", "yarn", "tmux"]

common_prefix = ["sudo"]

keymap_mode = "vim-insert"
