[[mgr.prepend_keymap]]
on = "<C-n>"
run = 'shell -- dragon-drop -x -a -i -T "$@"'


[[mgr.prepend_keymap]]
on = "<C-w>"
for = "linux"
run = 'shell -- ~/bin/global/select-background "$1"'
desc = "Set as wallpaper"

[[mgr.prepend_keymap]]
on = "y"
run = [
  'shell -- echo "$@" | xclip -i -selection clipboard -t text/uri-list',
  "yank",
]

[[mgr.prepend_keymap]]
on = ["g", "b"]
run = "cd ~/Documents/books"
desc = "Go to Books"

[[mgr.prepend_keymap]]
on = ["g", "s"]
run = "cd ~/Share"
desc = "Go to Share"

[[mgr.prepend_keymap]]
on = ["g", "f"]
run = "cd /usr/share/fonts/bryant-fonts"
desc = "Go to Ssytem Fonts"

[[mgr.prepend_keymap]]
on = ["g", "m"]
run = "cd /run/media"
desc = "Go to Media"


[[mgr.prepend_keymap]]
on = ["g", "w"]
run = "cd ~/Documents/github/media/images/wallpapers"
desc = "Go to wallpapers"

[[mgr.prepend_keymap]]
on = "p"
run = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"

# keymap.toml
[[mgr.prepend_keymap]]
on = "T"
run = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

# compress options
[[mgr.prepend_keymap]]
on = ["c", "a", "a"]
run = "plugin compress"
desc = "Archive selected files"

[[mgr.prepend_keymap]]
on = ["c", "a", "p"]
run = "plugin compress -p"
desc = "Archive selected files (password)"

[[mgr.prepend_keymap]]
on = ["c", "a", "h"]
run = "plugin compress -ph"
desc = "Archive selected files (password+header)"

[[mgr.prepend_keymap]]
on = ["c", "a", "l"]
run = "plugin compress -l"
desc = "Archive selected files (compression level)"

[[mgr.prepend_keymap]]
on = ["c", "a", "u"]
run = "plugin compress -phl"
desc = "Archive selected files (password+header+level)"
