[[mgr.prepend_keymap]]
on = "<C-n>"
run = 'shell -- dragon-drop -x -a -i -T "$@"'


[[mgr.prepend_keymap]]
on = "<C-w>"
for = "linux"
run = 'shell -- ~/bin/global/select-background "$1"'
desc = "Set as wallpaper"

[[mgr.prepend_keymap]]
on = "y"
run = [
  'shell -- echo "$@" | xclip -i -selection clipboard -t text/uri-list',
  "yank",
]

[[mgr.prepend_keymap]]
on = ["g", "b"]
run = "cd ~/Documents/books"
desc = "Go to Books"

[[mgr.prepend_keymap]]
on = ["g", "m"]
run = "cd /run/media"
desc = "Go to Media"


[[mgr.prepend_keymap]]
on = ["g", "w"]
run = "cd ~/Documents/github/media/images/wallpapers"
desc = "Go to wallpapers"
