add_newline = false

format = """
$directory\
$character"""

# Directory configuration
[directory]
truncation_length = 2
truncate_to_repo = false
style = "bold #a48faf"

[character]
error_symbol = "[󰁕](bold #FF0000)"
vimcmd_symbol = "[󰁕](bold #24c760)"
success_symbol = "[󰁕](bold #644F6F)"
