[user]
name = "Bryant Paz"
email = "pazbryant7@outlook.com"

[ui]
default-command = "log"

[aliases]
push = ["git", "push"]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
